# -*- coding: utf-8 -*-
"""CS4410Homework3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13GbEi8QWBHEum47VhKtJFugeeTwI8ZeU
"""

# Commented out IPython magic to ensure Python compatibility.
from sklearn import datasets
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
# %matplotlib inline

iris = datasets.load_iris()

X = iris.data
y = iris.target

k_range = range(1,31)
k_scores = []

for k in k_range:
  knn = KNeighborsClassifier(n_neighbors=k)
  scores = cross_val_score(knn,X,y,cv=10)
  k_scores.append(scores.mean())

k_scores

plt.plot(k_range, k_scores)
plt.xlabel("Value of K for KNN")
plt.ylabel("Cross-Validated Accuracy")
plt.show()

plt.plot(k_range, k_scores)
plt.xlabel("Value of K for KNN")
plt.ylabel("Cross-Validated Accuracy")
plt.xlim([11,15])
plt.ylim(min(k_scores[10:15]), max(k_scores[10:15]))


plt.show()

from sklearn.model_selection import GridSearchCV

param_grid = dict(n_neighbors=k_range)

gs = GridSearchCV(knn, param_grid, cv=10)

gs.fit(X,y)

print(gs.best_params_)
print(gs.best_score_)
print(gs.best_estimator_)